const types = {
  MOVIESLIST_FETCH_START: "MOVIESLIST_FETCH_START",
  MOVIESLIST_FETCH_SUCCESS: "MOVIESLIST_FETCH_SUCCESS",
  MOVIESLIST_FETCH_ERROR: "MOVIESLIST_FETCH_ERROR",

  PLANETS_FETCH_START: "PLANETS_FETCH_START",
  PLANETS_FETCH_SUCCESS: "PLANETS_FETCH_SUCCESS",
  PLANETS_FETCH_ERROR: "PLANETS_FETCH_ERROR",

  SHIPS_FETCH_START: "SHIPS_FETCH_START",
  SHIPS_FETCH_SUCCESS: "SHIPS_FETCH_SUCCESS",
  SHIPS_FETCH_ERROR: "SHIPS_FETCH_ERROR",
};

export default types;
